Models/Todo.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TaskIt.Web.Models
{
    public class Todo
    {
        [Key]
        public long Id { get; set; }
        public string Title { get; set; }
        public string Owner { get; set; }
        public bool IsComplete { get; set; } = false;



    }
}

Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TaskIt.Web.Controllers
{
    [Authorize]
    public class TodosController : Controller
    {
        private readonly ITodoRepository todoRepository;
        
        //Using DI to inject the itodo interface so the controller can access its implementing class (todo repo).
        public TodosController(ITodoRepository _todoRepository)
        {
            todoRepository = _todoRepository;
           
        }


        [HttpGet]
        public IActionResult Index()
        {
            //Calling the todos repo to access the display all method then we filter the results so
            //the page displays todos to their respective user and not everything in the db.
            IEnumerable<Todo> allTodos = todoRepository.DisplayAllTodos().Where(t => t.Owner == User.Identity.Name);
            return View(allTodos);
        }

        [HttpGet]
        public IActionResult AddTodo() => View();

        [HttpPost]
        public IActionResult AddTodo(Todo todo)
        {
            //Creating a todo object and using the already populated properties of the tood model
            //passed as an argument to instanitate the new todo object.
            Todo _todo = new Todo()
            {
                Title = todo.Title,
                Owner = User.Identity.Name
            };

            if (_todo.Title == null) return View();

            todoRepository.AddTodo(_todo);
            TempData["success"] = "New Todo Was Added Successfully :)";
            return RedirectToAction("Index");
            
        }

        [HttpPost]
        public IActionResult RemoveTodo(long id)
        {
            todoRepository.RemoveTodo(id);
            TempData["success"] = "Todo Was Removed Successfully :)";
            return RedirectToAction("Index");
        }

        


       
    }
}

Views/Todos/AddTodo.cshtml
@model Todo

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<link rel="stylesheet" href="~/css/FormStyles.css" />

<div class="container  d-flex align-items-center justify-content-center mt-3">
    <div class="row  form-container mt-5" style="height: 18rem">
        <div class="col-1 left-side-form p-4">



        </div>

        <div class="col-11 right-side-form p-4">
            <form method="post" asp-controller="Todos" asp-action="AddTodo">
                <h3><i class="bi bi-plus-circle-fill"></i> Add New Todo</h3>
                <br>
                <div class="form-group mb-3">
                    <label class="form-label">Todo</label>
                    <input class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <input class="form-control" asp-for="Owner" hidden>



                <div class="form-group mb-3">
                    <button class="btn btn-primary mb-2" type="submit" style="width:8rem;"><i class="bi bi-plus-circle-fill"></i> Add Todo</button> <br />
                    <a class="btn btn-dark" asp-controller="Todos" asp-action="Index" style="width:8rem;"><i class="bi bi-arrow-left-circle-fill"></i> Go Back</a>
                </div>

            </form>

        </div>

    </div>
</div>

Views/Todos/Index.cshtml
@model IEnumerable<Todo>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<style>
    .btn-danger {
        background-color: rgb(242, 50, 50);
    }
</style>

<partial name="_NotificationPartial" />
<div class="container mt-5">
    

    <div class="row mb-5">
        <div class="col-8">
            <h1>Todos</h1>
        </div>

        <div class="col-4 text-end">
            <a class="main-btn" asp-controller="Todos" asp-action="AddTodo">Add New Todo</a>
        </div>


    </div>

    @foreach (Todo t in Model)
    {
        <div class="todos-table" >
            <div class="row mb-3">

                <div class="col-9">
                    <div class="todo-container row">
                        <h6 style="display: inline" class="col-10">@t.Title</h6>

                        <div class="col-1">
                            <a  asp-controller="Todos" asp-action="ViewTodo">View</a>
                        </div>
                    </div>
                </div>

                <div class="col-3 text-end" style="display: inline">
                    <form method="post">
                        <button class="btn btn-danger main-btn-todo" asp-controller="Todos" asp-action="RemoveTodo" asp-route-id="@t.Id"><i class="bi bi-trash"></i></button>
                    </form>
                    
                </div>
            </div>
        </div>
    }
</div>